name: Deploy to SFTP and Restart Services

on:
  push:
    branches:
      - main

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy API
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP1_USERNAME }}
          server: "cursehosting-mutual-12.cursehosting.com"
          port: 22
          local_path: './movie-recommendation-api/*'
          remote_path: '/'
          sftp_only: true
          password: ${{ secrets.SFTP_PASSWORD }}

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Frontend
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP2_USERNAME }}  # Assuming you might have a different username or secret for frontend
          server: "cursehosting-mutual-11.cursehosting.com"
          port: 22
          local_path: './movie-recommendation-frontend/*'
          remote_path: '/'
          sftp_only: true
          password: ${{ secrets.SFTP_PASSWORD }}

  restart-api:
    needs: [deploy-api]
    runs-on: ubuntu-latest
    steps:
      - name: Restart API Server
        run: |
          curl "https://panel.cursehosting.com/api/client/service/39cfea52/power" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" \
            -X POST \
            -d '{"signal": "restart"}'

  restart-frontend:
    needs: [deploy-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Restart Frontend Server
        run: |
          curl "https://panel.cursehosting.com/api/client/service/6b74f8f4/power" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" \
            -X POST \
            -d '{"signal": "restart"}'
