name: Liquibase Migration

on:
  push:
    branches:
      - main
    paths:
      - 'database-migrations/changelogs/**'

    
jobs:
  liquibase_migration:
    runs-on: ubuntu-latest

steps:
- uses: actions/checkout@v3
- uses: liquibase-github-actions/update@v4.27.0
  with:
    changelogFile: "database-migrations/changelogs/db.changelog-master.xml"
    url: ${{ secrets.DB_URL }}
    driver: "org.postgresql.Driver"
    password: ${{ secrets.DB_PASSWORD }}
    username: ${{ secrets.DB_USERNAME }}
